# Generated by Django 5.1.7 on 2025-03-28 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notas',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
    ]
